---
abstract: 'Automatically title-case headlines and title-texts.'
author:
  - 'Ido Perlmuter <ido@ido50.net>'
build_requires:
  Test::More: 0
  open: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.102160'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-EN-Titlecase-Simple
requires:
  Exporter: 0
  perl: 5.008
  utf8: 0
version: 0.1
